
export default {
	Button: require('./button/Button').default,
	Icon: require('./icon/Icon').default,
	Modals: require('./modals/Modals').default,
	Sliders: require('./sliders/Sliders').default,
	Timeline: require('./timeline/Timeline').default,
	Input: require('./input/Input').default,
	Form: require('./form/Form').default,
	FormItem: require('./form/FormItem').default,
	Sidebar: require('./sidebar/Sidebar').default,
	Modals: require('./modals/Modals').default,
	Sliders: require('./sliders/Sliders').default,
	Timeline: require('./timeline/Timeline').default,
	Alert: require('./alert/Alert').default,
	Select: require('./select/Select').default,
	ZZStyleLayout: require('./zzstyle/ZZStyleLayout').default,
	Table: require('./table/Table').default,
	Topbar: require('./topbar/Topbar').default,
	Tree: require('./tree/Tree').default, 
	TreeTable:require('./table/TreeTable').default,
	InfoPalette: require('./widgets/InfoPalette').default,
	Select:require('./select/Select').default,
	SelectOption:require('./select/SelectOption').default,
	TreeSelect:require('./select/TreeSelect').default,
	Input:require('./input/Input').default,
	InputGroup:require('./input/InputGroup').default,
	DatePicker:require('./input/DatePicker').default,
	InputGroupSelect:require('./input/InputGroupSelect').default,
	Textarea:require('./input/Textarea').default,
	Editor:require('./editor/Editor').default,
	Codebox:require('./codebox/Codebox').default
}
